### ISSUE TITLE
Crash With Just a Few Fish Mod

### ISSUE THREAD

**Issue by ghost** [TTFTCUTS/ATG#13] opened 2017-05-31 13:37 UTC
[crash-2017-05-31_14.14.19-server.txt](https://github.com/TTFTCUTS/ATG/files/1041663/crash-2017-05-31_14.14.19-server.txt)
please help, i reported to JAFF too. thanks.

**Comment by TTFTCUTS** [comment] 2017-05-31 14:46
Duplicate of #6 and #12, crash caused by another mod during ice population somehow. Might be related to the conditions caused by ATG such as increased height but isn't a crash originating in my code, since that line is identical to vanilla.

**Closed as completed by TTFTCUTS** 2017-05-31 14:46 UTC
